export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const USER_LOAD = "USER_LOAD";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const ADMIN_DASHBOARD_ERROR = "ADMIN_DASHBOARD_ERROR";
export const ADMIN_DASHBOARD_SUCCESS = "ADMIN_DASHBOARD_SUCCESS";

export const AUTHOR_DASHBOARD_ERROR = "AUTHOR_DASHBOARD_ERROR";
export const AUTHOR_DASHBOARD_SUCCESS = "AUTHOR_DASHBOARD_SUCCESS";

export const AUTHOR_PROFILE_ERROR = "AUTHOR_PROFILE_ERROR";
export const AUTHOR_PROFILE_SUCCESS = "AUTHOR_PROFILE_SUCCESS";

export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";

export const BOOK_ADDED = "BOOK_ADDED";
export const BOOK_ERROR = "BOOK_ERROR";
export const REMOVE_TXT = "REMOVE_TXT";

export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_ERROR = "UPDATE_ERROR";

export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";
export const BOOK_DELETE_FAIL = "BOOK_DELETE_FAIL";

export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";
export const BOOK_UPDATE_FAIL = "BOOK_UPDATE_FAIL";

export const BASKET_BOOK_ADDED = "BASKET_BOOK_ADDED";
export const BASKET_BOOK_FAIL = "BASKET_BOOK_FAIL";

export const INCREMENT_QTE_SUCCESS = "INCREMENT_QTE_SUCCESS";
export const INCREMENT_QTE_FAIL = "INCREMENT_QTE_FAIL";

export const BASKET_ADD_SUCCESS = "BASKET_ADD_SUCCESS";
export const BASKET_ADD_FAIL = "BASKET_ADD_FAIL";

export const GET_BASKET_ADD = "GET_BASKET_ADD";
export const GET_BASKET_FAIL = "GET_BASKET_FAIL";

export const DECREMENT_QTE_SUCCESS = "DECREMENT_QTE_SUCCESS";
export const DECREMENT_QTE_AFIL = "DECREMENT_QTE_AFIL";

export const DELETE_BASKET_SUCCESS = "DELETE_BASKET_SUCCESS";
export const DELETE_BASKET_FAIL = "DELETE_BASKET_FAIL";

export const UPDATE_SEND_SUCCESS = "UPDATE_SEND_SUCCESS";
export const UPDATE_SEND_FAIL = "UPDATE_SEND_FAIL";

export const INCREMENT_LIKE_SUCCESS = "INCREMENT_LIKE_SUCCESS";
export const INCREMENT_LIKE_FAIL = "INCREMENT_LIKE_FAIL";

export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";

export const AFETR_POST_MESSAGE = "AFETR_POST_MESSAGE";

